### ISSUE TITLE
Support for "dhcp-host=" Directive

### ISSUE THREAD

**Issue by Xtigyro** [lixingcong/dnsmasq-regex#1]
Hi Team - could we broaden the REGEX support and add such for the `dhcp-host=` directive?

**Comment by lixingcong** [comment]
I don't know how to implement that because I have no idea how dnsmasq works.

This repo just patch some files referring to the patches which were wide-spreading on the Internet (for older version).

**Comment by daluu** [comment]
Anyone in community able & willing to contribute to this feature request can help out then ;-)
