### ISSUE TITLE
Regex rules override all other allow rules, even if the regex is at the end

### ISSUE THREAD

**Issue by ghost** [lixingcong/dnsmasq-regex#14]
In my _dnsmasq.conf_ file, I have two rules:

```
# Allow address:
server=/firebaseio.com/#

# Block any address containing 4 numbers:
address=/:.*[0-9]{4,4}.*:/
```

Now if I do `dig firebaseio.com`, I get the correct server IP address. But if I do `dig s-usc1a-nss-2026.firebaseio.com` (which is covered by the regex), then I get a `NXDOMAIN/127.0.0.1` response.

Since the first rule exists before the second, logically it should override the regex. But it seems like it is not doing so. Is this the expected behaviour?

**Comment by lixingcong** [comment]
Try to read [README.md](https://github.com/lixingcong/dnsmasq-regex/blob/master/README.md) again, it explained:

> If the domain matched normal and regex servers, DNS query will be forwarded to the normal one.

**Comment by lixingcong** [comment]
No plan for fix it.

Any pull requests are welcome.
