### ISSUE TITLE
Forwarding DNS queries to all regex servers

### ISSUE THREAD

**Issue by PrathikPrakash** [lixingcong/dnsmasq-regex#15]
Understand that in the config file below, the domain `wx.qq.com` will be forwarded to upstream `1.1.1.1`, not `8.8.8.8`
```
server=/:\.qq\.com:/1.1.1.1
server=/:\.qq\.com:/8.8.8.8
```

How can I modify the code to forward the domain (regex entries in general) to both `1.1.1.1` and `8.8.8.8`?

**Comment by lixingcong** [comment]
No plan for this.

I am not a maintainer of upstream repo. In my opinion, sending all queries to regex server will cause perfermance issue.

**Comment by PrathikPrakash** [comment]
Modified patches to do this. This can be closed.
