### ISSUE TITLE
Add AUR install guide

### ISSUE THREAD

**Issue by CHN-beta** [lixingcong/dnsmasq-regex#4]
I have submitted the package to AUR (Archlinux User Repository), Archlinux users could install the package to their system easily by the package manager, using the following command:

```
yay -S dnsmasq-regex
```

Could you please add the information to `README.md`?

**Comment by lixingcong** [comment]
Thanks. Added in https://github.com/lixingcong/dnsmasq-regex/commit/74aee4264b9beb474c44ff74eeaf225cd076ad4e
