### ISSUE TITLE
"CNAME" responses are not filtered trough address=/: ... :/ regex

### ISSUE THREAD

**Issue by arainchik** [lixingcong/dnsmasq-regex#5]
Example of config file example_config.conf:

     # listening DNS port
     port=30000
     
     # do not read /etc/resolv.conf at all
     no-resolv
     
     # do not re-read /etc/resolv.conf when file was changed by ISP
     no-poll
     
     # default upstream dns server
     server=1.1.1.1
     
     address=/:setup.[a-zA-Z]+\.apple-dns\.net.:/10.10.10.10
     
     
     log-debug
     log-queries=extra
     log-facility=/dev/stdout
     keep-in-foreground
     no-daemon

Running the dnsquery -C example_config.conf

Direct query for "setup.fe.apple-dns.net" works as expected:

    username@mac:~$ dig @127.0.0.1 -p30000 -t A setup.fe.apple-dns.net. +short
    10.10.10.10

However when I query "setup.icloud.com", which is a CNAME pointing to "setup.fe.apple-dns.net" it does not get processed trough address=/: ... :/ regex:

    username@mac:~$ dig @127.0.0.1 -p30000 -t A setup.icloud.com +short
    setup.fe.apple-dns.net.
    17.248.190.138
    17.248.190.206
    17.248.190.112
    17.248.190.68
    17.248.168.72
    17.248.190.71
    17.248.168.68
    17.248.190.104

Expected behavior would be for setup.icloud.com  query to get "10.10.10.10" response, same as for setup.fe.apple-dns.net. Because setup.icloud.com is a CNAME pointing to setup.fe.apple-dns.net

**Comment by lixingcong** [comment]
Not support your feature yet

See also: https://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2021q4/015942.html
