### ISSUE TITLE
Feature Update

### ISSUE THREAD

**Issue by TorstenJahnke** [lixingcong/dnsmasq-regex#6]
Hi... Awesome work! But I recommend to change your Makefile to this to have the full power of dnsmasq:

```
# turn on/off for regex or regex_ipset
- DNSMASQ_COPTS="-DHAVE_REGEX -DHAVE_REGEX_IPSET"
+ DNSMASQ_COPTS="-DHAVE_IDN -DHAVE_DNSSEC -DHAVE_LUA -DHAVE_DBUS -DHAVE_libidn2 -DHAVE_CONNTRACK -DHAVE_REGEX -DHAVE_REGEX_IPSET -DHAVE_LUASCRIPT "
```
```
.PHONY: submodule
submodule:
-        cd dnsmasq && $(MAKE) COPTS=$(DNSMASQ_COPTS)
+        cd dnsmasq && $(MAKE) all-i18n COPTS=$(DNSMASQ_COPTS)
```
```
$(BIN):$(PATCHED)
-        cd dnsmasq && $(MAKE) COPTS=$(DNSMASQ_COPTS)
+        cd dnsmasq && $(MAKE) all-i18n COPTS=$(DNSMASQ_COPTS)
```
Now run make and you will have almost all options compiled into dnsmasq.
Keep up this great work!!!

**Comment by lixingcong** [comment]
Compile arguments is optional for users. Anyone could customize the them. 

This repo just focus on how to compile regex module. I am not the expert of dnsmasq. I copied the patch from Internet and make some adaptations to lateset version.
