### ISSUE TITLE
matching the host portion of a fqdn using the server construct

### ISSUE THREAD

**Issue by quistian** [lixingcong/dnsmasq-regex#9]
What would be the syntax in the configuration file say to match the fqdns with  a structured prefix. E.g.

A123TEST.bozo.net
C999HELLO.bozo.net

server=/:[A-D][0-9][0-9][0-9].*\.bozo\.net:/1.2.3.4

Does not seem to match the above queries and have them sent to 1.2.3.4

**Comment by lixingcong** [comment]
File /tmp/1.conf:

```
# listening DNS port
port=30000

# default upstream dns server
server=114.114.114.114
server=/:[A-D][0-9][0-9][0-9].*\.bozo\.net:/8.8.4.4
```

Run dnsmasq to debug:

```
./dnsmasq/src/dnsmasq  -d -C /tmp/1.conf -q
```

Run dig to resolve domain:

```
dig @localhost -p30000 A123TEST.bozo.net
```

Dnsmasq works like we expect:

```
dnsmasq: query[A] A123TEST.bozo.net from 127.0.0.1
dnsmasq: forwarded A123TEST.bozo.net to 8.8.4.4
dnsmasq: reply A123TEST.bozo.net is 72.52.179.174
```

**Comment by quistian** [comment]
Thanks... I did find the problem was on an OpenBSD system. When I installed from src on Ubuntu 20 all worked as advertised.
